name: Robot Bolsa Diario

on:
  schedule:
    - cron: '0 7 * * *' # 8:00 AM España
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar librerías
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 yfinance pandas tabulate

      - name: Ejecutar robot
        env:
          MI_CORREO: ${{ secrets.MI_CORREO }}
          MI_CLAVE: ${{ secrets.MI_CLAVE }}
        run: python robot_vip.py

